version: "3.7"

services:
  db:
    build: ./postgres
    container_name: tts_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - postgres/.env.dev
    ports:
      - 5432:5432
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  pgadmin:
    build:
      context: ./pgadmin
    container_name: tts_pgadmin
    restart: always
    env_file:
      - pgadmin/.env.dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
  
  # nginx:
  #   image: nginx:1-alpine
  #   container_name: tts_nginx
  #   ports:
  #     - 443:443
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/certs/:/etc/nginx/certs/

  django:
    build: ./django
    container_name: tts_django
    env_file:
      - django/.env.dev
    # command: ["python", "manage.py", "runserver_plus", "0.0.0.0:8000", "--cert-file", "certs/server.crt", "--key-file", "certs/server.key"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./django/:/usr/src/django/
    ports:
      - 8100:8000
      

  fetcher:
    build: ./fetcher
    container_name: tts_fetcher
    volumes:
      - ./fetcher/:/fetcher/

  redis_service:
    image: redis:6.2-bullseye
    container_name: tts_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    name: tts_postgres_data
  pgadmin_data:
