# Generated by Django 5.1.4 on 2025-02-16 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=10)),
                ('course_type', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('url', models.CharField(max_length=2000)),
                ('plan_url', models.CharField(max_length=2000)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseUnitEnrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nmec', models.CharField(max_length=32)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('admin_state', models.CharField(max_length=32)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course_unit_enrollments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DirectExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField(max_length=256)),
                ('issuer_nmec', models.CharField(max_length=32)),
                ('accepted', models.BooleanField()),
                ('canceled', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('admin_state', models.CharField(max_length=32)),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'direct_exchange',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'exchange_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeUrgentRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nmec', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=2048)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('admin_state', models.CharField(max_length=32)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'exchange_urgent_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('acronym', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField(max_length=256)),
                ('issuer_nmec', models.CharField(max_length=32)),
                ('accepted', models.BooleanField()),
                ('canceled', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('admin_state', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'marketplace_exchange',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('professor_acronym', models.CharField(blank=True, max_length=32, null=True)),
                ('professor_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'professor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lesson_type', models.CharField(max_length=3)),
                ('day', models.IntegerField()),
                ('start_time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration', models.DecimalField(decimal_places=1, max_digits=3)),
                ('location', models.CharField(max_length=31)),
                ('is_composed', models.IntegerField()),
                ('professor_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'slot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=16)),
                ('url', models.CharField(max_length=2000)),
                ('semester', models.IntegerField()),
                ('year', models.SmallIntegerField()),
                ('schedule_url', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('last_updated', models.DateTimeField()),
                ('hash', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.course')),
            ],
            options={
                'db_table': 'course_unit',
                'managed': True,
                'unique_together': {('id', 'course', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('last_updated', models.DateTimeField()),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
            ],
            options={
                'db_table': 'class',
                'managed': True,
                'unique_together': {('name', 'course_unit')},
            },
        ),
        migrations.CreateModel(
            name='CourseUnitEnrollmentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolling', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
                ('course_unit_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunitenrollments')),
            ],
            options={
                'db_table': 'course_unit_enrollment_options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DirectExchangeParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=256)),
                ('participant_nmec', models.CharField(max_length=32)),
                ('class_participant_goes_from', models.CharField(max_length=16)),
                ('class_participant_goes_to', models.CharField(max_length=16)),
                ('course_unit', models.CharField(max_length=64)),
                ('course_unit_id', models.CharField(max_length=16)),
                ('accepted', models.BooleanField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('direct_exchange', models.ForeignKey(db_column='direct_exchange', on_delete=django.db.models.deletion.DO_NOTHING, to='university.directexchange')),
            ],
            options={
                'db_table': 'direct_exchange_participants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeAdminCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.course')),
                ('exchange_admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.exchangeadmin')),
            ],
            options={
                'db_table': 'exchange_admin_courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeAdminCourseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
                ('exchange_admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.exchangeadmin')),
            ],
            options={
                'db_table': 'exchange_admin_course_units',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeExpirations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
            ],
            options={
                'db_table': 'exchange_expirations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeUrgentRequestOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_user_goes_from', models.CharField(max_length=16)),
                ('class_user_goes_to', models.CharField(max_length=16)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
                ('exchange_urgent_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.exchangeurgentrequests')),
            ],
            options={
                'db_table': 'exchange_urgent_request_options',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.faculty'),
        ),
        migrations.AddField(
            model_name='directexchange',
            name='marketplace_exchange',
            field=models.ForeignKey(blank=True, db_column='marketplace_exchange', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.marketplaceexchange'),
        ),
        migrations.CreateModel(
            name='MarketplaceExchangeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_unit_name', models.CharField(max_length=256)),
                ('course_unit_acronym', models.CharField(max_length=256)),
                ('course_unit_id', models.CharField(max_length=256)),
                ('class_issuer_goes_from', models.CharField(max_length=16)),
                ('class_issuer_goes_to', models.CharField(max_length=16)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('marketplace_exchange', models.ForeignKey(db_column='marketplace_exchange', on_delete=django.db.models.deletion.DO_NOTHING, to='university.marketplaceexchange')),
            ],
            options={
                'db_table': 'marketplace_exchange_class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentCourseMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmec', models.CharField(max_length=255)),
                ('fest_id', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.course')),
            ],
            options={
                'db_table': 'student_course_metadata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCourseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nmec', models.CharField(max_length=32)),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='university.class')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
            ],
            options={
                'db_table': 'user_course_units',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('id', 'faculty', 'year')},
        ),
        migrations.CreateModel(
            name='CourseMetadata',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='university.course')),
                ('course_unit_year', models.IntegerField()),
                ('ects', models.FloatField()),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
            ],
            options={
                'db_table': 'course_metadata',
                'managed': True,
                'unique_together': {('course', 'course_unit', 'course_unit_year')},
            },
        ),
        migrations.CreateModel(
            name='SlotClass',
            fields=[
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='university.slot')),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='university.class')),
            ],
            options={
                'db_table': 'slot_class',
                'managed': True,
                'unique_together': {('slot', 'class_field')},
            },
        ),
        migrations.CreateModel(
            name='SlotProfessor',
            fields=[
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='university.slot')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.professor')),
            ],
            options={
                'db_table': 'slot_professor',
                'managed': True,
                'unique_together': {('slot', 'professor')},
            },
        ),
    ]
