# Generated by Django 5.1.4 on 2025-09-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_class_vacancies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slotclass',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='slotprofessor',
            unique_together=set(),
        ),
    ]
