# Generated by Django 5.1.4 on 2025-09-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_slotclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slotclass',
            unique_together={('slot', 'class_field')},
        ),
        migrations.AlterUniqueTogether(
            name='slotprofessor',
            unique_together={('slot', 'professor')},
        ),
    ]
