# Generated by Django 5.1.12 on 2025-12-16 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_slotclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotclass',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slotclass',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.slot'),
        ),
    ]
