# Generated by Django 5.1.12 on 2025-12-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_slotclass_id_alter_slotclass_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotclass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
