# Generated by Django 5.1.4 on 2025-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_rename_class_user_goes_from_exchangeurgentrequestoptions_class_issuer_goes_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directexchange',
            name='last_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
