# Generated by Django 5.1.12 on 2025-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_exchangeurgentrequests_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directexchange',
            name='has_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
