# Generated by Django 5.1.12 on 2025-09-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_directexchange_has_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeurgentrequests',
            name='has_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplaceexchange',
            name='has_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
