# Generated by Django 5.1.12 on 2025-11-12 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_directexchange_last_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeadmincourses',
            name='exchange_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchangeadmin'),
        ),
        migrations.AlterField(
            model_name='exchangeadmincourseunits',
            name='exchange_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.exchangeadmin'),
        ),
    ]
