INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (0,'faup','Faculdade de Arquitetura (FAUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (1,'fbaup','Faculdade de Belas Artes (FBAUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (2,'fcup','Faculdade de Ciências (FCUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (3,'fcnaup','Faculdade de Ciências da Nutrição e da Alimentação (FCNAUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (4,'fadeup','Faculdade de Desporto (FADEUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (5,'fdup','Faculdade de Direito (FDUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (6,'fep','Faculdade de Economia (FEP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (7,'feup','Faculdade de Engenharia (FEUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (8,'ffup','Faculdade de Farmácia (FFUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (9,'flup','Faculdade de Letras (FLUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (10,'fmup','Faculdade de Medicina (FMUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (11,'fmdup','Faculdade de Medicina Dentária (FMDUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (12,'fpceup','Faculdade de Psicologia e de Ciências da Educação (FPCEUP)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (13,'icbas','Instituto de Ciências Biomédicas Abel Salazar (ICBAS)'); 
INSERT INTO faculty (`id`,`acronym`,`name`) VALUES (14,'pbs','Porto Business School'); 
